version: '3'

services:
  master:
    build:
      context: '.'
    ports:
     - "80:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
    environment:
      BLOCKSET_TOKEN: $BLOCKSET_TOKEN

  worker:
    build:
      context: '.'
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    environment:
      BLOCKSET_TOKEN: $BLOCKSET_TOKEN
